# Generated by Django 2.0.3 on 2020-05-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='userpass',
            field=models.CharField(max_length=20),
        ),
    ]
