# Generated by Django 2.0.3 on 2020-05-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20200526_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='userpass',
            field=models.CharField(max_length=100),
        ),
    ]
