# Generated by Django 2.0.3 on 2020-05-26 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20200526_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_code', models.IntegerField()),
                ('pro_type', models.CharField(max_length=100, verbose_name=100)),
                ('pro_price', models.FloatField(verbose_name='商品价格')),
                ('pro_kuwei', models.IntegerField()),
                ('pro_intro', models.TextField(verbose_name='产品备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.UserTable')),
            ],
        ),
    ]
